server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      access: unrestricted

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: cake-catalog-service
              uri: http://${CAKE_CATALOG_HOST}:8080
              predicates:
                  - Path=/cakecatalog/**

            - id: cake-catalog-images
              uri: http://${CAKE_CATALOG_HOST}:8080
              predicates:
                - Path=/images/**

            - id: order-service
              uri: http://${ORDER_SERVICE_HOST}:8081
              predicates:
                - Path=/order/**

            - id: rating-service
              uri: http://${RATING_SERVICE_HOST}:8082
              predicates:
                - Path=/rating/**

            - id: notification-service
              uri: http://${NOTIFICATION_SERVICE_HOST}:8083
              predicates:
                - Path=/notification/**
